In [41]:
import numpy as np
import pandas as pd

PATH = './data/'


import os
for dirname, _, filenames in os.walk(PATH):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./data/data_description.txt
./data/sample_submission.csv
./data/test.csv
./data/train.csv

## მონაცემების წაკითხვა და დაყოფა

In [42]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.width', None)        
pd.set_option('display.expand_frame_repr', False)

In [43]:
df = pd.read_csv(PATH + 'train.csv')
df.shape

(1460, 81)

In [44]:
df.head()

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType SaleCondition  SalePrice
0   1          60       RL         65.0     8450   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2003          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace       196.0        Gd        TA      PConc       Gd       TA           No          GLQ         706          Unf           0        150          856    GasA        Ex          Y      SBrkr       856       854             0       1710             1             0         2         1             3             1          Gd             8        Typ           0         NaN     Attchd       2003.0          RFn           2         548         TA         TA          Y           0           61              0          0            0         0    NaN   NaN         NaN        0       2    2008       WD        Normal     208500
1   2          20       RL         80.0     9600   Pave   NaN      Reg         Lvl    AllPub       FR2       Gtl      Veenker      Feedr       Norm     1Fam     1Story            6            8       1976          1976     Gable  CompShg     MetalSd     MetalSd        NaN         0.0        TA        TA     CBlock       Gd       TA           Gd          ALQ         978          Unf           0        284         1262    GasA        Ex          Y      SBrkr      1262         0             0       1262             0             1         2         0             3             1          TA             6        Typ           1          TA     Attchd       1976.0          RFn           2         460         TA         TA          Y         298            0              0          0            0         0    NaN   NaN         NaN        0       5    2007       WD        Normal     181500
2   3          60       RL         68.0    11250   Pave   NaN      IR1         Lvl    AllPub    Inside       Gtl      CollgCr       Norm       Norm     1Fam     2Story            7            5       2001          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace       162.0        Gd        TA      PConc       Gd       TA           Mn          GLQ         486          Unf           0        434          920    GasA        Ex          Y      SBrkr       920       866             0       1786             1             0         2         1             3             1          Gd             6        Typ           1          TA     Attchd       2001.0          RFn           2         608         TA         TA          Y           0           42              0          0            0         0    NaN   NaN         NaN        0       9    2008       WD        Normal     223500
3   4          70       RL         60.0     9550   Pave   NaN      IR1         Lvl    AllPub    Corner       Gtl      Crawfor       Norm       Norm     1Fam     2Story            7            5       1915          1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN         0.0        TA        TA     BrkTil       TA       Gd           No          ALQ         216          Unf           0        540          756    GasA        Gd          Y      SBrkr       961       756             0       1717             1             0         1         0             3             1          Gd             7        Typ           1          Gd     Detchd       1998.0          Unf           3         642         TA         TA          Y           0           35            272          0            0         0    NaN   NaN         NaN        0       2    2006       WD       Abnorml     140000
4   5          60       RL         84.0    14260   Pave   NaN      IR1         Lvl    AllPub       FR2       Gtl      NoRidge       Norm       Norm     1Fam     2Story            8            5       2000          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace       350.0        Gd        TA      PConc       Gd       TA           Av          GLQ         655          Unf           0        490         1145    GasA        Ex          Y      SBrkr      1145      1053             0       2198             1             0         2         1             4             1          Gd             9        Typ           1          TA     Attchd       2000.0          RFn           3         836         TA         TA          Y         192           84              0          0            0         0    NaN   NaN         NaN        0      12    2008       WD        Normal     250000

In [45]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df, test_size=0.2, random_state=1603)
train.shape, test.shape

((1168, 81), (292, 81))

In [46]:
x_train = train.drop(['Id', 'SalePrice'], axis=1)
x_test = test.drop(['Id', 'SalePrice'], axis=1)
y_train = train['SalePrice']
y_test = test['SalePrice']

In [47]:
cat_cols = x_train.select_dtypes(include='object').columns
num_cols = x_train.select_dtypes(exclude='object').columns

print(f"Categorical columns ({len(cat_cols)}): {cat_cols}")
print(f"Numerical columns ({len(num_cols)}): {num_cols}")

Categorical columns (43): Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')
Numerical columns (36): Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces',
       'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold'],
      dtype='object')

## პირველი მარტივი მოდელი

### feature engineering

In [48]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn import set_config

set_config(transform_output="pandas")

# ჩავანაცვლოთ რიცხვები საშუალოთი, კატეგორიები რიცხვებით (NaN ან უცნობი -> -1)
preprocessor = ColumnTransformer([
    ("num", SimpleImputer(strategy="mean"), num_cols),
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1, encoded_missing_value=-1), cat_cols)
])
preprocessor.set_output(transform="pandas")

x_train = pd.DataFrame(
    preprocessor.fit_transform(train),
    columns=preprocessor.get_feature_names_out()
)

x_test = pd.DataFrame(
    preprocessor.transform(test),
    columns=preprocessor.get_feature_names_out()
)

In [49]:
x_train.head()

      num__MSSubClass  num__LotFrontage  num__LotArea  num__OverallQual  num__OverallCond  num__YearBuilt  num__YearRemodAdd  num__MasVnrArea  num__BsmtFinSF1  num__BsmtFinSF2  num__BsmtUnfSF  num__TotalBsmtSF  num__1stFlrSF  num__2ndFlrSF  num__LowQualFinSF  num__GrLivArea  num__BsmtFullBath  num__BsmtHalfBath  num__FullBath  num__HalfBath  num__BedroomAbvGr  num__KitchenAbvGr  num__TotRmsAbvGrd  num__Fireplaces  num__GarageYrBlt  num__GarageCars  num__GarageArea  num__WoodDeckSF  num__OpenPorchSF  num__EnclosedPorch  num__3SsnPorch  num__ScreenPorch  num__PoolArea  num__MiscVal  num__MoSold  num__YrSold  cat__MSZoning  cat__Street  cat__Alley  cat__LotShape  cat__LandContour  cat__Utilities  cat__LotConfig  cat__LandSlope  cat__Neighborhood  cat__Condition1  cat__Condition2  cat__BldgType  cat__HouseStyle  cat__RoofStyle  cat__RoofMatl  cat__Exterior1st  cat__Exterior2nd  cat__MasVnrType  cat__ExterQual  cat__ExterCond  cat__Foundation  cat__BsmtQual  cat__BsmtCond  cat__BsmtExposure  cat__BsmtFinType1  cat__BsmtFinType2  cat__Heating  cat__HeatingQC  cat__CentralAir  cat__Electrical  cat__KitchenQual  cat__Functional  cat__FireplaceQu  cat__GarageType  cat__GarageFinish  cat__GarageQual  cat__GarageCond  cat__PavedDrive  cat__PoolQC  cat__Fence  cat__MiscFeature  cat__SaleType  cat__SaleCondition
1374             60.0         85.000000       10625.0               7.0               5.0          2005.0             2005.0              0.0              0.0              0.0          1026.0            1026.0         1026.0          932.0                0.0          1958.0                0.0                0.0            2.0            1.0                3.0                1.0                9.0              1.0       2005.000000              3.0            936.0            154.0             210.0                 0.0             0.0               0.0            0.0           0.0          7.0       2008.0            1.0          1.0        -1.0            3.0               3.0             0.0             4.0             0.0               21.0              2.0              2.0            0.0              5.0             1.0            1.0               5.0               5.0             -1.0             2.0             4.0              2.0            2.0            3.0                3.0                5.0                5.0           1.0             0.0              1.0              3.0               2.0              5.0               2.0              1.0                0.0              4.0              4.0              2.0         -1.0        -1.0              -1.0            8.0                 4.0
458              70.0         70.434511        5100.0               8.0               7.0          1925.0             1996.0              0.0              0.0              0.0           588.0             588.0          833.0          833.0                0.0          1666.0                0.0                0.0            1.0            0.0                3.0                1.0                7.0              1.0       1925.000000              1.0            228.0            192.0              63.0                 0.0             0.0               0.0            0.0           0.0          6.0       2008.0            4.0          1.0         0.0            3.0               3.0             0.0             4.0             0.0               17.0              2.0              2.0            0.0              5.0             3.0            1.0              11.0              15.0             -1.0             3.0             2.0              2.0            3.0            3.0                3.0                5.0                5.0           1.0             1.0              1.0              3.0               2.0              5.0               2.0              5.0                2.0              4.0              4.0              2.0         -1.0         2.0              -1.0            8.0                 4.0
1011             90.0         75.000000        9825.0               5.0               5.0          1965.0             1965.0              0.0              0.0              0.0             0.0               0.0         1664.0            0.0                0.0          1664.0                0.0                0.0            2.0            0.0                4.0                2.0                8.0              0.0       1978.775271              0.0              0.0              0.0               0.0                 0.0             0.0               0.0            0.0           0.0          5.0       2010.0            3.0          1.0        -1.0            3.0               3.0             0.0             4.0             0.0                7.0              2.0              2.0            2.0              2.0             3.0            1.0               1.0               1.0             -1.0             3.0             4.0              1.0           -1.0           -1.0               -1.0               -1.0               -1.0           1.0             4.0              0.0              3.0               3.0              5.0              -1.0             -1.0               -1.0             -1.0             -1.0              2.0         -1.0        -1.0              -1.0            8.0                 4.0
877              60.0         74.000000        8834.0               9.0               5.0          2004.0             2005.0            216.0           1170.0              0.0           292.0            1462.0         1462.0          762.0                0.0          2224.0                1.0                0.0            2.0            1.0                4.0                1.0               10.0              1.0       2004.000000              3.0            738.0            184.0               0.0                 0.0             0.0               0.0            0.0           0.0          6.0       2009.0            3.0          1.0        -1.0            3.0               3.0             0.0             4.0             0.0               16.0              2.0              2.0            0.0              5.0             3.0            1.0              12.0              13.0              2.0             2.0             4.0              2.0            0.0            3.0                3.0                2.0                5.0           1.0             0.0              1.0              3.0               0.0              5.0               2.0              1.0                0.0              4.0              4.0              2.0         -1.0        -1.0              -1.0            8.0                 4.0
794              60.0         70.434511       10832.0               7.0               5.0          1994.0             1996.0              0.0              0.0              0.0           712.0             712.0         1086.0          809.0                0.0          1895.0                0.0                0.0            2.0            1.0                3.0                1.0                7.0              1.0       1994.000000              2.0            409.0            143.0              46.0                 0.0             0.0               0.0            0.0         500.0         10.0       2008.0            3.0          1.0        -1.0            0.0               3.0             0.0             0.0             0.0                8.0              2.0              2.0            0.0              5.0             1.0            1.0               8.0               8.0             -1.0             2.0             4.0              2.0            2.0            3.0                3.0                5.0                5.0           1.0             0.0              1.0              3.0               2.0              5.0               4.0              1.0                0.0              4.0              4.0              2.0         -1.0        -1.0               1.0            8.0                 4.0

In [50]:
import mlflow
import mlflow.sklearn
import dagshub

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

REPO_OWNER = 'adola23'
REPO_NAME = 'HousePricesML'

dagshub.init(repo_owner=REPO_OWNER, repo_name=REPO_NAME, mlflow=True)

Initialized MLflow to track repo "adola23/HousePricesML"

Repository adola23/HousePricesML initialized!

### პირველი მარტივი მოდელის ექსპერიმენტი

In [ ]:
# პირველი მარტივი მოდელის ლოგი
mlflow.set_experiment("BasicLinearRegression1")
with mlflow.start_run():

    model = LinearRegression()
    model.fit(x_train, y_train)

    y_pred = model.predict(x_test)

    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    y_pred = np.maximum(0, y_pred)
    y_pred_log = np.log1p(y_pred)
    y_test_log = np.log1p(y_test)
    rmse_log = np.sqrt(mean_squared_error(y_test_log, y_pred_log))

    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_param("test_size", 0.2)


    mlflow.log_metric("rmse_log", rmse_log)
    mlflow.log_metric("mse", mse)
    mlflow.log_metric("r2", r2)


    mlflow.sklearn.log_model(model, "model")
    mlflow.sklearn.log_model(preprocessor, "preprocessor")

    print("RMSE:", rmse_log)
    print("MSE:", mse)
    print("R2:", r2)

2026/03/30 20:05:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/30 20:05:02 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/30 20:05:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/30 20:05:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/30 20:05:17 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!

RMSE: 0.7234127265910805
MSE: 1660796505.099019
R2: 0.7978805909677699
🏃 View run resilient-bat-932 at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/1/runs/ae26bf6cf2784e4881b9d76c6af5b158
🧪 View experiment at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/1

## უკეთესი მოდელის feature engineering და ექსპერიმენტი ერთად

In [51]:
# ახლა ვცადოთ რიცხვები ჩავანაცვლოთ საშუალოებით, კატეგორიულები თუ #კატეგორია <= one_hot_threshold მაშინ one hot encoding 
# თუ > 3 მაშინ woe და ბოლოს კორელაციის ფილტრს მოვდებთ (ეს აღარ არის კოდში, iv + woe მოვაშორე რადგან კარგი შედეგი არ მომცა)

# აქ არის one_hot + კორელაციის ფილტრი + ლოგარითმზე ტრენინგი რაც rmse-ს მინიმიზაციაში გვეხმარება

x_train = train.drop(['Id', 'SalePrice'], axis=1)
x_test = test.drop(['Id', 'SalePrice'], axis=1)
y_train = train['SalePrice']
y_test = test['SalePrice']

In [52]:
import joblib # ამას ვიყენებ რომ იგივე პრეპროცესინგი გავაკეთო model_inference-ში

In [ ]:
X_train, X_test = x_train.copy(), x_test.copy()
# ეს kaggle-ს საიტზე ეწერა რომ შესაძლოა კარგი ყოფილიყო
train_idx = X_train[X_train['GrLivArea'] < 4000].index
X_train, y_train = X_train.loc[train_idx], y_train.loc[train_idx]


mlflow.set_experiment("LinearRegression ONE_HOT +  CORRELATION + train on log(y)")
with mlflow.start_run():
    corr_threshold = 0.99
    one_hot_threshold = 30

    mlflow.log_param("correlation_threshold", corr_threshold)
    mlflow.log_param("one_hot_threshold", one_hot_threshold)

    # ======== Feature engineering ===========

    train_means = {col: x_train[col].mean() for col in num_cols}

    # რიცხვები საშუალოთი ჩავანაცვლოთ
    for col in num_cols:
        mean_value = X_train[col].mean()
        X_train[col].fillna(mean_value, inplace=True)
        X_test[col].fillna(mean_value, inplace=True)

    # კატეგორიულები
    one_hot_cols_list = []
    one_hot_columns = {}
    one_hot_used_cols = []
    chosen_for_one_hot = 0
    for col in cat_cols:
        n_unique = X_train[col].nunique()
        if n_unique <= one_hot_threshold:
            # one hot encoding
            dummies_train = pd.get_dummies(X_train[col], prefix=col)
            dummies_test = pd.get_dummies(X_test[col], prefix=col)

            dummies_test = dummies_test.reindex(columns=dummies_train.columns, fill_value=0)

            one_hot_columns[col] = list(dummies_train.columns)
            one_hot_used_cols.append(col)
            
            X_train = pd.concat([X_train.drop(columns=[col]), dummies_train], axis=1)
            X_test = pd.concat([X_test.drop(columns=[col]), dummies_test], axis=1)

            
            one_hot_cols_list += list(dummies_train.columns)
            chosen_for_one_hot += 1
    

    # ======== Feature Selection ===========

    mlflow.log_param("dropped_cat_columns", len(cat_cols) - chosen_for_one_hot)
    # დავტოვოთ შესაბამისი სვეტები
    selected_cols = list(num_cols) + one_hot_cols_list
    X_train_filtered = X_train[selected_cols].copy()
    X_test_filtered = X_test[selected_cols].copy()

    # კორელაციის ფილტრი
    corr_matrix = X_train_filtered.corr().abs()
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

    to_drop = [col for col in upper.columns if any(upper[col] > corr_threshold)]
    mlflow.log_dict({"dropped_columns": to_drop}, "correlation_dropped.json")

    X_train_filtered.drop(columns=to_drop, inplace=True)
    X_test_filtered.drop(columns=to_drop, inplace=True)


    # პრეპროცესინგის მონაცემების შენახვა
    preprocessing_artifacts = {
        "num_cols": num_cols,
        "cat_cols": cat_cols,
        "train_means": train_means,
        "one_hot_used_cols": one_hot_used_cols,
        "one_hot_columns": one_hot_columns,
        "selected_cols": selected_cols,
        "to_drop": to_drop
    }
    joblib.dump(preprocessing_artifacts, "preprocessing.pkl")
    mlflow.log_artifact("preprocessing.pkl")

    # ======== Model Training ===========
    
    # რადგან საბოლოო მეტრიკა kaggle-ზე არის rmse 
    # მოდელს დავატრენინგებ y-ის ლოგარითმზე 
    y_train_log = np.log1p(y_train)
    y_test_log = np.log1p(y_test)

    model = LinearRegression()

    model.fit(X_train_filtered, y_train_log)

    y_pred_log = model.predict(X_test_filtered)
    y_train_pred_log = model.predict(X_train_filtered)

    rmse_log_train = np.sqrt(mean_squared_error(y_train_log, y_train_pred_log))
    rmse_log = np.sqrt(mean_squared_error(y_test_log, y_pred_log))

    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_param("test_size", 0.2)


    mlflow.log_metric("rmse_log", rmse_log)


    mlflow.sklearn.log_model(model, "model")

    print("RMSE:", rmse_log)
    print("TRAIN RMSE:", rmse_log_train)

2026/04/13 15:37:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/13 15:37:41 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RMSE: 0.14581318573374127
TRAIN RMSE: 0.0846857184554563
🏃 View run blushing-wolf-229 at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/3/runs/988e71d8fd5141f9a16ed0d40ab031ef
🧪 View experiment at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/3

## მესამე ექსპერიმენტი

## feature engineering

In [53]:
# scaler-ის გამოყენების დამატება და დამატებითი column-ების დამატება 
# სხვადასხვა წყვილებით რომ უფრო მეტი კავშირი დაინახოს მოდელმა

X_train, X_test = x_train.copy(), x_test.copy()
train_idx = X_train[X_train['GrLivArea'] < 4000].index
X_train, y_train = X_train.loc[train_idx], y_train.loc[train_idx]

Y_train = y_train.copy()
Y_test = y_test.copy()

Y_train_log = np.log1p(y_train)
Y_test_log = np.log1p(y_test)

# დავამატოთ თითოეული სვეტისთვის ცალკე სვეტი რომელიც გვეტყვის ეს სვეტი არის თუ არა NaN
for col in num_cols:
    if X_train[col].isna().sum() > 0:
        X_train[f"{col}_isnan"] = X_train[col].isna().astype(int)
        X_test[f"{col}_isnan"] = X_test[col].isna().astype(int)



# რიცხვები საშუალოთი ჩავანაცვლოთ
for col in num_cols:
    mean_value = X_train[col].mean()
    X_train[col].fillna(mean_value, inplace=True)
    X_test[col].fillna(mean_value, inplace=True)


# დავამატოთ სვეტების ლოგარითმებიც რადგან შესაძლოა ლოგარითმის პოვნაში უკეთ გამოგვადგეს 
for col in num_cols:
    if (X_train[col] > 0).all():
        X_train[f"{col}_log"] = np.log1p(X_train[col])
        X_test[f"{col}_log"] = np.log1p(X_test[col])


col_x_col_count = 10
# ავიღოთ ათი პასუხთან ყველაზე კორელირებული სვეტი და მათი წყვილები დავამატოთ
corr = X_train[num_cols].corrwith(y_train).abs().sort_values(ascending=False)
top_cols = corr.head(col_x_col_count).index

for i in range(len(top_cols)):
    for j in range(i+1, len(top_cols)):
        c1 = top_cols[i]
        c2 = top_cols[j]
        X_train[f"{c1}_x_{c2}"] = X_train[c1] * X_train[c2]
        X_test[f"{c1}_x_{c2}"] = X_test[c1] * X_test[c2]

In [54]:
ohe_dummies = {}
# one hot encoding
for col in cat_cols:
    # one hot encoding
    dummies_train = pd.get_dummies(X_train[col], prefix=col)
    dummies_test = pd.get_dummies(X_test[col], prefix=col)
    ohe_dummies[col] = dummies_train.columns
    dummies_test = dummies_test.reindex(columns=dummies_train.columns, fill_value=0)
    X_train = pd.concat([X_train.drop(columns=[col]), dummies_train], axis=1)
    X_test = pd.concat([X_test.drop(columns=[col]), dummies_test], axis=1)

In [55]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# scaler-ს აღარ ვიყენებ რადგან უარეს შედეგს მაძლევდა. 
X_train_scaled = X_train
X_test_scaled  = X_test

### Feature Selection

In [56]:
# RFE

from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE

lr = LinearRegression()

rfe_feature_count = 100
n_features_to_select = min(rfe_feature_count, X_train_scaled.shape[1])

rfe = RFE(estimator=lr, n_features_to_select=n_features_to_select)

X_rfe = rfe.fit_transform(X_train_scaled, Y_train_log)

# keep selected feature names
selected_features = X_train_scaled.columns[rfe.support_]
print("Selected features:", list(selected_features))

Selected features: ['OverallQual', 'YearRemodAdd', 'BsmtFullBath', 'GarageYrBlt', 'YrSold', 'GarageYrBlt_isnan', 'LotArea_log', 'OverallQual_log', 'OverallCond_log', 'YearBuilt_log', 'YearRemodAdd_log', '1stFlrSF_log', 'GrLivArea_log', 'TotRmsAbvGrd_log', 'GarageYrBlt_log', 'YrSold_log', 'MSZoning_C (all)', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL', 'Street_Grvl', 'Street_Pave', 'Utilities_AllPub', 'Utilities_NoSeWa', 'LandSlope_Gtl', 'LandSlope_Mod', 'LandSlope_Sev', 'Neighborhood_CollgCr', 'Neighborhood_Crawfor', 'Neighborhood_Edwards', 'Neighborhood_Gilbert', 'Neighborhood_MeadowV', 'Neighborhood_Mitchel', 'Neighborhood_NWAmes', 'Neighborhood_NoRidge', 'Neighborhood_OldTown', 'Neighborhood_SawyerW', 'Neighborhood_StoneBr', 'Condition1_Artery', 'Condition1_RRAe', 'Condition1_RRNn', 'Condition2_Artery', 'Condition2_Feedr', 'Condition2_PosA', 'Condition2_PosN', 'Condition2_RRAn', 'BldgType_Duplex', 'HouseStyle_1.5Unf', 'HouseStyle_2.5Fin', 'RoofStyle_Flat', 'RoofStyle_Gable', 'RoofStyle_Gambrel', 'RoofStyle_Hip', 'RoofStyle_Shed', 'RoofMatl_Membran', 'RoofMatl_Metal', 'RoofMatl_WdShake', 'Exterior1st_AsphShn', 'Exterior1st_BrkComm', 'Exterior1st_BrkFace', 'Exterior2nd_Stucco', 'MasVnrType_BrkCmn', 'ExterQual_Ex', 'ExterCond_Ex', 'Foundation_Wood', 'BsmtCond_Gd', 'BsmtCond_Po', 'BsmtCond_TA', 'BsmtExposure_Av', 'BsmtExposure_Gd', 'BsmtExposure_Mn', 'BsmtExposure_No', 'Heating_Floor', 'Heating_GasA', 'Heating_GasW', 'Heating_Grav', 'Heating_OthW', 'HeatingQC_Po', 'Electrical_Mix', 'KitchenQual_Ex', 'Functional_Maj2', 'Functional_Mod', 'Functional_Typ', 'FireplaceQu_Po', 'GarageQual_Ex', 'GarageQual_Fa', 'GarageQual_Po', 'GarageCond_Ex', 'GarageCond_Po', 'PavedDrive_P', 'PoolQC_Gd', 'SaleType_COD', 'SaleType_ConLI', 'SaleType_ConLw', 'SaleType_New', 'SaleType_WD', 'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Normal', 'SaleCondition_Partial']

In [59]:
X_train_filtered = X_train_scaled[selected_features]
X_test_filtered = X_test_scaled[selected_features]


# პრეპროცესინგის მონაცემების შენახვა
preprocessing_artifacts = {
    "num_cols": num_cols,
    "cat_cols": cat_cols,
    "train_means": train_means,
    "top_cols": top_cols,
    "ohe_dummies": ohe_dummies,
    "selected_features": selected_features,
}
joblib.dump(preprocessing_artifacts, "preprocessing.pkl")

['preprocessing.pkl']

### train + ექსპერიმენტი

In [60]:
mlflow.set_experiment("LinearRegression scaling + rfe + logs + col_X_col + one_hot")
with mlflow.start_run():

    mlflow.log_param("col_X_col top col count", col_x_col_count)
    mlflow.log_param("rfe feature count", rfe_feature_count)
    mlflow.log_param("selected_features", selected_features)

    model = LinearRegression()

    model.fit(X_train_filtered, Y_train_log)

    Y_pred_log = model.predict(X_test_filtered)

    rmse_log = np.sqrt(mean_squared_error(Y_test_log, Y_pred_log))

    mlflow.log_param("model_type", "LinearRegression")
    mlflow.log_param("test_size", 0.2)


    mlflow.log_metric("rmse_log", rmse_log)


    mlflow.sklearn.log_model(model, "model")
    mlflow.log_artifact("preprocessing.pkl")
    
    print("RMSE:", rmse_log)

2026/04/13 16:16:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/13 16:16:51 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RMSE: 0.14372302476720536
🏃 View run skillful-stork-867 at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/4/runs/b54ea972ec944b638e156d8c09a9760c
🧪 View experiment at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/4

# მეოთხე ექსპერიმენტი წინას preprocessing-ით

In [ ]:
from sklearn.tree import DecisionTreeRegressor

mlflow.set_experiment("DecisionTree rfe + logs + col_X_col + one_hot")
with mlflow.start_run():

    mlflow.log_param("col_X_col top col count", col_x_col_count)
    mlflow.log_param("rfe feature count", rfe_feature_count)
    mlflow.log_param("selected_features", selected_features)

    model = DecisionTreeRegressor(
        random_state=42,
        max_depth=5,
        min_samples_split=30,
        min_samples_leaf=20,
    )   

    model.fit(X_train_filtered, Y_train_log)

    Y_pred_log = model.predict(X_test_filtered)
    Y_train_pred_log = model.predict(X_train_filtered)

    rmse_log = np.sqrt(mean_squared_error(Y_test_log, Y_pred_log))
    rmse_log_train = np.sqrt(mean_squared_error(Y_train_log, Y_train_pred_log))
    mlflow.log_param("model_type", "DecisionTreeRegressor")
    mlflow.log_param("test_size", 0.2)

    mlflow.log_param("max_depth", model.max_depth)
    mlflow.log_param("min_samples_split", model.min_samples_split)
    mlflow.log_param("min_samples_leaf", model.min_samples_leaf)
    mlflow.log_param("random_state", 42)

    mlflow.log_metric("rmse_log", rmse_log)

    mlflow.sklearn.log_model(model, "model")
    mlflow.log_artifact("preprocessing.pkl")

    print("RMSE:", rmse_log)
    print("TRAIN RMSE:", rmse_log_train)

2026/04/13 18:48:00 INFO mlflow.tracking.fluent: Experiment with name 'RandomForestRegressor rfe + logs + col_X_col + one_hot' does not exist. Creating a new experiment.
2026/04/13 18:48:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/04/13 18:48:09 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

RMSE: 0.20319213057775157
TRAIN RMSE: 0.13518165874762533
🏃 View run persistent-quail-842 at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/6/runs/f289527a07ea4f8a807163b0acaaa0d3
🧪 View experiment at: https://dagshub.com/adola23/HousePricesML.mlflow/#/experiments/6